name: Deploy Resume Frontend on S3

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: S3 Sync
        run: aws s3 sync . s3://cloud-resume-laripping --exclude ".*"
      - name: Invalidate Cloudfront Caches
        run: aws cloudfront create-invalidation --distribution-id E6HWW76UUKEQD --paths "/*"